-- 1. Таблица рейтингов (MPA)
CREATE TABLE IF NOT EXISTS mpas (
    mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

-- 2. Таблица фильмов
CREATE TABLE IF NOT EXISTS films (
    film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(200),
    release_date DATE,
    duration INTEGER,
    mpa_id INTEGER REFERENCES mpas(mpa_id) ON DELETE RESTRICT -- Рейтинг удалять нельзя, если есть фильмы с ним
);

-- 3. Таблица жанров
CREATE TABLE IF NOT EXISTS genres (
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

-- 4. Связка фильмов и жанров
CREATE TABLE IF NOT EXISTS film_genres (
    film_id BIGINT REFERENCES films(film_id) ON DELETE CASCADE, -- Если удален фильм, удаляем связь
    genre_id INTEGER REFERENCES genres(genre_id) ON DELETE CASCADE, -- Если удален жанр, удаляем связь
    PRIMARY KEY (film_id, genre_id)
);

-- 5. Таблица пользователей
CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE, -- ❗️ Запрещаем дубликаты email
    login VARCHAR(255) NOT NULL UNIQUE, -- ❗️ Запрещаем дубликаты login
    name VARCHAR(255),
    birthday DATE
);

-- 6. Таблица лайков
CREATE TABLE IF NOT EXISTS film_likes (
    film_id BIGINT REFERENCES films(film_id) ON DELETE CASCADE, -- Удаляем лайк, если удален фильм
    user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE, -- Удаляем лайк, если удален юзер
    PRIMARY KEY (film_id, user_id)
);

-- 7. Таблица дружбы
CREATE TABLE IF NOT EXISTS friendships (
    user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    friend_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    is_mutual BOOLEAN DEFAULT false,
    PRIMARY KEY (user_id, friend_id)
);